FROM node:18-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# COPY dist/final.js .

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 5000

# CMD ["node", "final.js"]

CMD ["npm", "run", "dev"]