# action.yml
name: Github Actions with docker
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  action-with-docker:
    runs-on: ubuntu-latest
    steps:
      name: hello world
      description: 'Greet someone and record the time'
      inputs:
        who-to-greet:  # id of input
          description: 'Who to greet'
          required: true
          default: 'World'
      outputs:
        time: # id of output
          description: 'The time we greeted you'
      runs:
        using: 'docker'
        image: 'Dockerfile'
        args:
          - ${{ inputs.who-to-greet }}